# Site settings
title: Combify | Combify blog
description: "A minimal blog for Combify"
url: "http://blog.combify.net"
author:
  name: "Dave Ramautar"
  url: "http://davecharley.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
